route:
    receiver: 'slack'
 
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'bruno'
            channel: '#GENERAL'
            api_url: 'https://hooks.slack.com/services/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'
