global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'cadAdvisor-devops'
rule_files:
        - '/etc/prometheus/alert-rules.yml'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
          - targets: ['alertmanager:9093']
     
scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
          - targets: ['cadvisor:8080', http://ec2-54-203-218-71.us-west-2.compute.amazonaws.com:8080/metrics]    
