global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'cadAdvisor-devops'
rule_files:
        - '/etc/prometheus/alert-rules.yml'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
          - targets: ['alertmanager:9093']
     
scrape_configs:

- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
          - targets: ['cadvisor:8080', '172.31.44.142:8080']

#- job_name:  'cadvisor2'
#    scrape_interval: 5s
#    static_configs:
#     - targets: ['172.31.43.23:8000']
